name: Discord Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U discord.py gspread google-auth

      - name: Run bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}

          LOWER_REQUEST_CHANNEL_ID: "1469311152671428680"
          UPPER_REQUEST_CHANNEL_ID: "1469310757018665012"
          LOWER_UPPER_LIST_CHANNEL_ID: "1469310840837640242"

          INCOLLE_REQUEST_CHANNEL_ID: "1469310789209817301"
          INCOLLE_LIST_CHANNEL_ID: "1469310877340668139"

          LU_SPREADSHEET_ID: ${{ secrets.LU_SPREADSHEET_ID }}
          LU_SHEET_NAME: "チャレンジ指導回答"

          LU_MENTION_SPREADSHEET_ID: ${{ secrets.LU_MENTION_SPREADSHEET_ID }}
          LU_MENTION_SHEET_NAME: "メンション"

          INC_SPREADSHEET_ID: ${{ secrets.INC_SPREADSHEET_ID }}
          INC_SHEET_NAME: "チャレンジ指導回答"

          INC_MENTION_SPREADSHEET_ID: ${{ secrets.INC_MENTION_SPREADSHEET_ID }}
          INC_MENTION_SHEET_NAME: "メンション"

        run: python bot.py
